using System.Text.Json;
using CoreServer.Domain.Entities;
using CoreServer.Domain.Enums;

namespace CoreServer.Infrastructure.Persistence.Seed;

public static class CoreServerSeed
{
    public static async Task SeedAsync(CoreServerDbContext dbContext)
    {
        if (!dbContext.EventPatterns.Any())
        {
            // Seed all 6 event types with multiple training vectors.
            // Vectors follow the DBSCAN feature order:
            // [workersCount, modelDataVolume, changesCount, collisionCount, approvalDelayDays, reworkCount]
            //
            // ModelDataVolume is generated by DigitalTwin as: 150 + progress*4.5 + rand*50
            // At 50% progress ≈ 350-450; at 80% ≈ 500-600. Training vectors cover this range.
            dbContext.EventPatterns.AddRange(
                // ApprovalDelayed — long approval delay, low collisions
                new EventPattern
                {
                    Id = Guid.NewGuid(),
                    Name = "Approval Delay Pattern A",
                    Vector = JsonSerializer.Serialize(new[] { 4d, 420d, 1d, 0d, 7d, 1d }),
                    EventType = EventType.ApprovalDelayed,
                    AverageDelayImpact = 1.18,
                    CreatedAt = DateTime.UtcNow
                },
                new EventPattern
                {
                    Id = Guid.NewGuid(),
                    Name = "Approval Delay Pattern B",
                    Vector = JsonSerializer.Serialize(new[] { 5d, 520d, 1d, 0d, 5d, 0d }),
                    EventType = EventType.ApprovalDelayed,
                    AverageDelayImpact = 1.18,
                    CreatedAt = DateTime.UtcNow
                },
                // CollisionDetected — high collision count
                new EventPattern
                {
                    Id = Guid.NewGuid(),
                    Name = "Collision Spike Pattern A",
                    Vector = JsonSerializer.Serialize(new[] { 7d, 480d, 3d, 7d, 1d, 2d }),
                    EventType = EventType.CollisionDetected,
                    AverageDelayImpact = 1.12,
                    CreatedAt = DateTime.UtcNow
                },
                new EventPattern
                {
                    Id = Guid.NewGuid(),
                    Name = "Collision Spike Pattern B",
                    Vector = JsonSerializer.Serialize(new[] { 8d, 590d, 2d, 6d, 0d, 1d }),
                    EventType = EventType.CollisionDetected,
                    AverageDelayImpact = 1.12,
                    CreatedAt = DateTime.UtcNow
                },
                // DesignRequirementChanged — high changes count
                new EventPattern
                {
                    Id = Guid.NewGuid(),
                    Name = "Design Change Pattern A",
                    Vector = JsonSerializer.Serialize(new[] { 5d, 460d, 8d, 0d, 0d, 0d }),
                    EventType = EventType.DesignRequirementChanged,
                    AverageDelayImpact = 1.10,
                    CreatedAt = DateTime.UtcNow
                },
                new EventPattern
                {
                    Id = Guid.NewGuid(),
                    Name = "Design Change Pattern B",
                    Vector = JsonSerializer.Serialize(new[] { 6d, 540d, 7d, 1d, 0d, 0d }),
                    EventType = EventType.DesignRequirementChanged,
                    AverageDelayImpact = 1.10,
                    CreatedAt = DateTime.UtcNow
                },
                // DocumentationReturned — moderate rework, some delay
                new EventPattern
                {
                    Id = Guid.NewGuid(),
                    Name = "Documentation Return Pattern A",
                    Vector = JsonSerializer.Serialize(new[] { 6d, 500d, 2d, 0d, 2d, 4d }),
                    EventType = EventType.DocumentationReturned,
                    AverageDelayImpact = 1.15,
                    CreatedAt = DateTime.UtcNow
                },
                new EventPattern
                {
                    Id = Guid.NewGuid(),
                    Name = "Documentation Return Pattern B",
                    Vector = JsonSerializer.Serialize(new[] { 5d, 580d, 1d, 0d, 3d, 4d }),
                    EventType = EventType.DocumentationReturned,
                    AverageDelayImpact = 1.15,
                    CreatedAt = DateTime.UtcNow
                },
                // ResourceShortage — low workers count
                new EventPattern
                {
                    Id = Guid.NewGuid(),
                    Name = "Resource Shortage Pattern A",
                    Vector = JsonSerializer.Serialize(new[] { 1d, 390d, 0d, 0d, 0d, 0d }),
                    EventType = EventType.ResourceShortage,
                    AverageDelayImpact = 1.14,
                    CreatedAt = DateTime.UtcNow
                },
                new EventPattern
                {
                    Id = Guid.NewGuid(),
                    Name = "Resource Shortage Pattern B",
                    Vector = JsonSerializer.Serialize(new[] { 2d, 470d, 1d, 0d, 0d, 0d }),
                    EventType = EventType.ResourceShortage,
                    AverageDelayImpact = 1.14,
                    CreatedAt = DateTime.UtcNow
                },
                // ExpertReviewFailed — rework + delay combo
                new EventPattern
                {
                    Id = Guid.NewGuid(),
                    Name = "Expert Review Fail Pattern A",
                    Vector = JsonSerializer.Serialize(new[] { 6d, 510d, 1d, 0d, 3d, 4d }),
                    EventType = EventType.ExpertReviewFailed,
                    AverageDelayImpact = 1.20,
                    CreatedAt = DateTime.UtcNow
                },
                new EventPattern
                {
                    Id = Guid.NewGuid(),
                    Name = "Expert Review Fail Pattern B",
                    Vector = JsonSerializer.Serialize(new[] { 7d, 600d, 2d, 0d, 4d, 3d }),
                    EventType = EventType.ExpertReviewFailed,
                    AverageDelayImpact = 1.20,
                    CreatedAt = DateTime.UtcNow
                });
        }

        if (!dbContext.Projects.Any())
        {
            var projectId = Guid.NewGuid();
            var start = DateTime.UtcNow.Date;
            dbContext.Projects.Add(new Project
            {
                Id = projectId,
                Name = "Demo BIM Design Project",
                StartDate = start,
                EndDate = start.AddDays(20),
                Works =
                [
                    new Work { Id = Guid.NewGuid(), ProjectId = projectId, Name = "Work1", StartDate = start, EndDate = start.AddDays(5), PlannedDuration = 5, CurrentDuration = 5 },
                    new Work { Id = Guid.NewGuid(), ProjectId = projectId, Name = "Work2", StartDate = start.AddDays(5), EndDate = start.AddDays(11), PlannedDuration = 6, CurrentDuration = 6 },
                    new Work { Id = Guid.NewGuid(), ProjectId = projectId, Name = "Work3", StartDate = start.AddDays(5), EndDate = start.AddDays(10), PlannedDuration = 5, CurrentDuration = 5 }
                ]
            });
        }

        await dbContext.SaveChangesAsync();
    }
}
